# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Levantamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_sem_att', models.PositiveSmallIntegerField(null=True)),
                ('ss_programado', models.DateField(null=True)),
                ('ss_real', models.DateField(null=True)),
                ('ss_hechox', models.CharField(blank=True, max_length=50)),
                ('ss_nota', models.TextField(blank=True)),
                ('ss_validacion', models.DateField(null=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=50)),
                ('supervisor', models.CharField(choices=[('OL', 'Oscar López'), ('PQ', 'Pablo Quezada'), ('FJ', 'Francisco Juárez'), ('MS', 'Miguel Salgado'), ('LG', 'Luis Gutierrez'), ('OM', 'Oscar Marín'), ('LD', 'Lino De La Rosa'), ('JP', 'Juan Pablo'), ('ME', 'Martín Elías'), ('JG', 'Jaime García'), ('GJ', 'Gerardo Jiménez'), ('AB', 'Arturo Bautista')], max_length=50)),
                ('cuadrilla', models.CharField(blank=True, max_length=50)),
                ('cos_sem_att', models.PositiveSmallIntegerField(null=True)),
                ('cos_programado', models.DateField(null=True)),
                ('cos_real', models.DateField(null=True)),
                ('cof_sem_att', models.PositiveSmallIntegerField(null=True)),
                ('cof_programado', models.DateField(null=True)),
                ('cof_real', models.DateField(null=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_contrata', models.BooleanField(default=True)),
                ('contrata_view', models.BooleanField(default=False)),
                ('mastec_admin', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=3)),
                ('gerente_att', models.CharField(blank=True, max_length=50)),
                ('coordinador_att', models.CharField(blank=True, max_length=50)),
                ('cellowner', models.CharField(blank=True, max_length=50)),
                ('telefono_cellowner', models.CharField(blank=True, max_length=50)),
                ('coordinador_mastec', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('idatt_mastec', models.CharField(blank=True, max_length=50)),
                ('site_id', models.CharField(blank=True, max_length=20)),
                ('id3g', models.CharField(blank=True, max_length=20)),
                ('idgsm', models.CharField(blank=True, max_length=20)),
                ('idlte', models.CharField(blank=True, max_length=20)),
                ('ididen', models.CharField(blank=True, max_length=20)),
                ('lat_decimal', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('long_decimal', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('nombre_sitio', models.CharField(max_length=50)),
                ('prioridad', models.CharField(blank=True, max_length=2)),
                ('jerarquia', models.CharField(blank=True, max_length=30)),
                ('sitios_dependientes', models.CharField(blank=True, max_length=20)),
                ('comentarios_att', models.TextField(blank=True)),
                ('cluster', models.CharField(blank=True, max_length=50)),
                ('problema_acceso', models.TextField(blank=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sitio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_actividad', models.CharField(choices=[('NOSS', 'Por Levantar'), ('SS', 'Levantado'), ('CWS', 'Proceso CW'), ('CWF', 'Terminado CW'), ('CWF', 'Entregado')], max_length=10)),
                ('avance', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(choices=[('OK', 'Activo'), ('CA', 'Cancelado'), ('SU', 'Suspendido')], max_length=30)),
                ('creado', models.DateField(auto_now_add=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Disclaimer.Sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnto', to='Disclaimer.Sitio'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_mnt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levantamiento',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levantamientos', to='Disclaimer.Sitio'),
        ),
        migrations.AddField(
            model_name='levantamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
