# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Levantamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_sem_att', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ss_programado', models.DateField(blank=True, null=True)),
                ('ss_real', models.DateField(blank=True, null=True)),
                ('ss_hechox', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_nota', models.TextField(blank=True, null=True)),
                ('ss_recibido', models.DateField(blank=True, null=True)),
                ('ss_validacion', models.DateField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, choices=[('DH', 'David Hernández'), ('EKSA', 'ECCASA'), ('ETL', 'ECOTEL'), ('FS', 'Franco & Soto'), ('FD', 'Freddy'), ('GICOM', 'Grupo ICOM'), ('GIP', 'Grupo IPE'), ('GVI', 'Grupo VALBRI'), ('GST', 'Grupo SET'), ('JAVCRUZ', 'Javier De La Cruz'), ('JAVJ', 'Javier Jiménez'), ('JJ', 'Juan Jesús'), ('MC', 'Macario Hernández'), ('MQ', 'Maqueda'), ('VK', 'Ve-Ca'), ('VI', 'Viadeza')], max_length=50, null=True)),
                ('supervisor', models.CharField(blank=True, choices=[('ALS', 'Alan Santana'), ('AS', 'Antonio Salazar'), ('AB', 'Arturo Bautista'), ('FO', 'Fabián Olan'), ('FJ', 'Francisco Juárez'), ('GJ', 'Gerardo Jiménez'), ('JG', 'Jaime García'), ('JP', 'Juan Pablo Flores'), ('LG', 'Luis Gutierrez'), ('LD', 'Lino De La Rosa'), ('ME', 'Martín Elías'), ('MS', 'Miguel Salgado'), ('OL', 'Oscar López'), ('OM', 'Oscar Marín'), ('PQ', 'Pablo Quezada'), ('PS', 'Pedro Santiago')], max_length=50, null=True)),
                ('cuadrilla', models.CharField(blank=True, max_length=50, null=True)),
                ('cos_sem_att', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cos_programado', models.DateField(blank=True, null=True)),
                ('cos_real', models.DateField(blank=True, null=True)),
                ('cof_sem_att', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cof_programado', models.DateField(blank=True, null=True)),
                ('cof_real', models.DateField(blank=True, null=True)),
                ('fech_odk', models.DateField(blank=True, null=True)),
                ('nota_sitio', models.TextField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_contrata', models.BooleanField(default=True)),
                ('contrata_view', models.BooleanField(default=False)),
                ('mastec_admin', models.BooleanField(default=False)),
                ('proveedor', models.CharField(blank=True, choices=[('DH', 'David Hernández'), ('EKSA', 'ECCASA'), ('ETL', 'ECOTEL'), ('FS', 'Franco & Soto'), ('FD', 'Freddy'), ('GICOM', 'Grupo ICOM'), ('GIP', 'Grupo IPE'), ('GVI', 'Grupo VALBRI'), ('GST', 'Grupo SET'), ('JAVCRUZ', 'Javier De La Cruz'), ('JAVJ', 'Javier Jiménez'), ('JJ', 'Juan Jesús'), ('MC', 'Macario Hernández'), ('MQ', 'Maqueda'), ('VK', 'Ve-Ca'), ('VI', 'Viadeza')], max_length=50, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=3, null=True)),
                ('gerente_att', models.CharField(blank=True, max_length=50, null=True)),
                ('coordinador_att', models.CharField(blank=True, max_length=50, null=True)),
                ('cellowner', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_cellowner', models.CharField(blank=True, max_length=50, null=True)),
                ('coordinador_mastec', models.CharField(max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('idatt_mastec', models.CharField(max_length=50, null=True)),
                ('id3g', models.CharField(max_length=20, null=True)),
                ('idgsm', models.CharField(max_length=20, null=True)),
                ('idlte', models.CharField(max_length=20, null=True)),
                ('ididen', models.CharField(max_length=20, null=True)),
                ('lat_decimal', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('long_decimal', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('nombre_sitio', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=2, null=True)),
                ('jerarquia', models.CharField(max_length=30, null=True)),
                ('sitios_dependientes', models.CharField(max_length=20, null=True)),
                ('comentarios_att', models.TextField(blank=True, null=True)),
                ('cluster', models.CharField(max_length=50, null=True)),
                ('problema_acceso', models.TextField(blank=True, null=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sitio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_actividad', models.CharField(choices=[('NOSS', 'Por Levantar'), ('SS', 'Levantado'), ('CWS', 'Proceso CW'), ('CWF', 'Terminado CW'), ('CWF', 'Entregado')], max_length=10)),
                ('avance', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(choices=[('OK', 'Activo'), ('CA', 'Cancelado'), ('SU', 'Suspendido')], max_length=30)),
                ('creado', models.DateField(auto_now_add=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='Disclaimer.Sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.CreateModel(
            name='Volumetrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volPre_recepcion', models.DateField(blank=True, null=True)),
                ('volPre_monto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9)),
                ('vol_po_solitada', models.DateField(blank=True, null=True)),
                ('vol_po_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('vol_final_recibido', models.DateField(blank=True, null=True)),
                ('vol_final_vobo', models.CharField(blank=True, choices=[('ALS', 'Alan Santana'), ('AS', 'Antonio Salazar'), ('AB', 'Arturo Bautista'), ('FO', 'Fabián Olan'), ('FJ', 'Francisco Juárez'), ('GJ', 'Gerardo Jiménez'), ('JG', 'Jaime García'), ('JP', 'Juan Pablo Flores'), ('LG', 'Luis Gutierrez'), ('LD', 'Lino De La Rosa'), ('ME', 'Martín Elías'), ('MS', 'Miguel Salgado'), ('OL', 'Oscar López'), ('OM', 'Oscar Marín'), ('PQ', 'Pablo Quezada'), ('PS', 'Pedro Santiago')], max_length=50, null=True)),
                ('vol_envio_att', models.DateField(blank=True, null=True)),
                ('vol_monto_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('vol_valida_att', models.DateField(blank=True, null=True)),
                ('vol_creado', models.DateField(auto_now_add=True)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitio_presupto', to='Disclaimer.Sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_presupto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('contra_view', 'Contratista Can View'), ('mastec_view', 'Mastec Can View')),
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnto', to='Disclaimer.Sitio'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_mnt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='levantamiento',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levantamientos', to='Disclaimer.Sitio'),
        ),
        migrations.AddField(
            model_name='levantamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
