# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disclaimer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levantamiento',
            name='ss_hechox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='levantamiento',
            name='ss_nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levantamiento',
            name='ss_programado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levantamiento',
            name='ss_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levantamiento',
            name='ss_sem_att',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levantamiento',
            name='ss_validacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cof_programado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cof_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cof_sem_att',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cos_programado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cos_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cos_sem_att',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cuadrilla',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='proveedor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='cellowner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='cluster',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='comentarios_att',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='coordinador_att',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='coordinador_mastec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='gerente_att',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='id3g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='idatt_mastec',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='idgsm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='ididen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='idlte',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='jerarquia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='prioridad',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='problema_acceso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='region',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='site_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='sitios_dependientes',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='telefono_cellowner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
