# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disclaimer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='id3g',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='idatt_mastec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='idgsm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='ididen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='idlte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
