# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disclaimer', '0002_auto_20170810_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='jerarquia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='prioridad',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='sitios_dependientes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
