# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disclaimer', '0003_auto_20170331_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('OL', 'Oscar López'), ('PQ', 'Pablo Quezada'), ('FJ', 'Francisco Juárez'), ('MS', 'Miguel Salgado'), ('LG', 'Luis Gutierrez'), ('OM', 'Oscar Marín'), ('LD', 'Lino De La Rosa'), ('JP', 'Juan Pablo'), ('ME', 'Martín Elías'), ('JG', 'Jaime García'), ('GJ', 'Gerardo Jiménez'), ('AB', 'Arturo Bautista')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='supervisor',
            field=models.CharField(blank=True, choices=[('OL', 'Oscar López'), ('PQ', 'Pablo Quezada'), ('FJ', 'Francisco Juárez'), ('MS', 'Miguel Salgado'), ('LG', 'Luis Gutierrez'), ('OM', 'Oscar Marín'), ('LD', 'Lino De La Rosa'), ('JP', 'Juan Pablo'), ('ME', 'Martín Elías'), ('JG', 'Jaime García'), ('GJ', 'Gerardo Jiménez'), ('AB', 'Arturo Bautista')], max_length=50, null=True),
        ),
    ]
