# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disclaimer', '0003_auto_20170810_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='cluster',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
