# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disclaimer', '0004_auto_20170810_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('AP', 'Ancla Proyectos'), ('CM', 'Color Machines'), ('DH', 'David Hernández'), ('EKSA', 'ECCASA'), ('ETL', 'ECOTEL'), ('FS', 'Franco & Soto'), ('FD', 'Freddy'), ('GICOM', 'Grupo ICOM'), ('GIP', 'Grupo IPE'), ('GVI', 'Grupo VALBRI'), ('GST', 'Grupo SET'), ('IR', 'IRed'), ('JAVCRUZ', 'Javier De La Cruz'), ('JAVJ', 'Javier Jiménez'), ('JJ', 'Juan Jesús'), ('MC', 'Macario Hernández'), ('MQ', 'Maqueda'), ('VK', 'Ve-Ca'), ('VI', 'Viadeza'), ('IR', 'IRed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('AP', 'Ancla Proyectos'), ('CM', 'Color Machines'), ('DH', 'David Hernández'), ('EKSA', 'ECCASA'), ('ETL', 'ECOTEL'), ('FS', 'Franco & Soto'), ('FD', 'Freddy'), ('GICOM', 'Grupo ICOM'), ('GIP', 'Grupo IPE'), ('GVI', 'Grupo VALBRI'), ('GST', 'Grupo SET'), ('IR', 'IRed'), ('JAVCRUZ', 'Javier De La Cruz'), ('JAVJ', 'Javier Jiménez'), ('JJ', 'Juan Jesús'), ('MC', 'Macario Hernández'), ('MQ', 'Maqueda'), ('VK', 'Ve-Ca'), ('VI', 'Viadeza'), ('IR', 'IRed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='avance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
