# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-13 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disclaimer', '0005_auto_20170331_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumetrico',
            name='volPre_monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('DH', 'David Hernández'), ('EKSA', 'ECCASA'), ('ETL', 'ECOTEL'), ('FS', 'Franco & Soto'), ('FD', 'Freddy'), ('GICOM', 'Grupo ICOM'), ('GIP', 'Grupo IPE'), ('GVI', 'Grupo VALBRI'), ('GST', 'Grupo SET'), ('JAVCRUZ', 'Javier De La Cruz'), ('JAVJ', 'Javier Jiménez'), ('JJ', 'Juan Jesús'), ('MC', 'Macario Hernández'), ('MQ', 'Maqueda'), ('VK', 'Ve-Ca'), ('VI', 'Viadeza')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('DH', 'David Hernández'), ('EKSA', 'ECCASA'), ('ETL', 'ECOTEL'), ('FS', 'Franco & Soto'), ('FD', 'Freddy'), ('GICOM', 'Grupo ICOM'), ('GIP', 'Grupo IPE'), ('GVI', 'Grupo VALBRI'), ('GST', 'Grupo SET'), ('JAVCRUZ', 'Javier De La Cruz'), ('JAVJ', 'Javier Jiménez'), ('JJ', 'Juan Jesús'), ('MC', 'Macario Hernández'), ('MQ', 'Maqueda'), ('VK', 'Ve-Ca'), ('VI', 'Viadeza')], max_length=50, null=True),
        ),
    ]
